---
version: "3.40"

vars:
  SOURCES:
    sh: find . -name "*.go" -type f -not -iname mock.go -not -path "./.devenv/*" -not -path "./.direnv/*" | xargs echo
  PACKAGES:
    sh: go list ./... | xargs echo

tasks:
  clean:
    desc: Remove all temporary build artifacts
    cmds:
      - go clean -i ./...
      - rm -rf bin/ dist/

  generate:
    desc: Generate code
    cmds:
      - go generate {{ .PACKAGES }}

  fmt:
    desc: Run standard formatter
    cmds:
      - gofmt -s -w {{ .SOURCES }}

  vet:
    desc: Run vet linting
    cmds:
      - go vet {{ .PACKAGES }}

  lint:
    desc: Run revive linting
    cmds:
      - for PKG in {{ .PACKAGES }}; do go tool github.com/mgechev/revive -config revive.toml -set_exit_status $PKG || exit 1; done;

  golangci:
    desc: Run golangci linter
    cmds:
      - go tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test -coverprofile coverage.out {{ .PACKAGES }}

  build:
    desc: Build all required binary artifacts
    cmds:
      - go build -v
          -tags 'netgo'
          -ldflags '-s -w -extldflags "-static" -X "{{ .IMPORT }}/pkg/version.String={{ .VERSION }}" -X "{{ .IMPORT }}/pkg/version.Revision={{ .REVISION }}" -X "{{ .IMPORT }}/pkg/version.Date={{ now | date "20060102" }}"'
          -o bin/terrastate{{if eq OS "windows"}}.exe{{end}}
          ./cmd/terrastate
    env:
      CGO_ENABLED: "0"
    vars:
      IMPORT: github.com/webhippie/terrastate
      VERSION:
        sh: if [[ -z "${CI_COMMIT_TAG}" ]]; then git rev-parse --short HEAD; else echo "${CI_COMMIT_TAG#v}"; fi
      REVISION:
        sh: git rev-parse --short HEAD

  build:release:
    desc: Generate a release with goreleaser
    cmds:
      - goreleaser release --clean

  build:snapshot:
    desc: Generate a snapshot with goreleaser
    cmds:
      - goreleaser release --clean --snapshot

  watch:
    desc: Run reloading development server
    cmds:
      - task: build
      - bin/terrastate server
    watch: true
    method: none
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'
      - 'pkg/**/*.tmpl'
    env:
      TERRASTATE_LOG_LEVEL: "{{ .TERRASTATE_LOG_LEVEL | default \"debug\" }}"

...
