FROM arm32v6/alpine:3.20@sha256:5c7e326e3c8a8c51654a6c5d94dac98d7f6fc4b2a762d86aaf67b7e76a6aee46 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 8080 8081
VOLUME ["/var/lib/terrastate"]
ENTRYPOINT ["/usr/bin/terrastate"]
CMD ["server"]

ENV TERRASTATE_STORAGE /var/lib/terrastate

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/terrastate /usr/bin/terrastate
