---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup golang
        id: golang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod

      - name: Run generate
        id: generate
        run: make generate

      - name: Run vet
        id: vet
        run: make vet

      - name: Run staticcheck
        id: staticcheck
        run: make staticcheck

      - name: Run lint
        id: lint
        run: make lint

      - name: Run build
        id: build
        run: make build

      - name: Run test
        id: test
        run: make test

      - name: Coverage report
        id: codacy
        if: github.ref == 'refs/heads/master'
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          force-coverage-parser: go

...
